### ISSUE TITLE
Problema al obtener el listado de todas las etiquetas disponibles

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree-client#103]
Hola Migasfree Team!!

Me acabo de dar cuenta de un problema fundamental que se da en Ubuntu 18.04, y es que el comando **migasfree-tags -a** no funciona.  Este funciona sin problemas en Ubuntu 14.04. 
No es problema de la versión del cliente **migasfree-client** ya que tras probar con la versión **4.16** y la **4.17** en Ubuntu 18.04 ocurre lo mismo, no funciona. Por contra, otros comandos como **migasfree-tags -g** o **migasfree-tags -c** funcionan sin problemas.  ¿Sabéis que puede estar pasando?

```
# migasfree-tags -g
"ENT-ALUMNO" "ENT-PROFESOR"

```
```
# migasfree-tags -c ENT-ALUMNO ENT-PROFESOR
...
Etiquetas seleccionadas: ['ENT-ALUMNO', 'ENT-PROFESOR']

```
```
# migasfree-tags -a
{}     <= ¡¡Problema!! Debería aparecer el listado de todas las etiquetas

```
También aprovecho para comentaros que el 	**migasfree -g** o **migasfree --register** que usamos en Ubuntu 14.04 tampoco funciona, pero esto no es ningún problema ya que el equipo cliente se registra en el mismo momento que hace un **migasfree -u**.

Muchísimas gracias de antemano. Saludos!!

**Comment by agacias** [comment]
Comprueba por favor que tienes para ese proyecto (Ubuntu 18) asignadas las etiquetas en algún despliegue.

**Comment by amartinr1977** [comment]
Hola Alberto!!

Perdonad el descuido.  Estamos actualmente haciendo las últimas pruebas para tratar de liberar definitivamente la versión de Vitalinux basada en Ubuntu 18.04, y justamente el servidor migasfree contra el que estaba haciendo las pruebas no tenía asignadas la lista de etiquetas a ningún repositorio.  Pensaba que podría ser alguna librería de python o similar que se había actualizado y que había provocado ese comportamiento erróneo.  Cierro la issue.  Perdonad de nuevo el descuido.

Muchísimas gracias de antemano. Saludos!!
