### ISSUE TITLE
Warining: apt-key ouput shoud not be parsed (stdout is not a terminal)

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree-client#104]
Versión del cliente: 4.16.
S.O Anfitrión: Ubuntu 18.04
Al registrar un equipo nuevo se produce ésta salida de error, cuando se están recnaod las claves de migasfree. 
Posiblemente se debe a que ésta versión de apt-key se "queja" ahora cuando le metes una clave por entrada estándar, produciendo ésa salida

**Comment by jact** [comment]
https://stackoverflow.com/questions/48162574/how-to-circumvent-apt-key-output-should-not-be-parsed
