### ISSUE TITLE
Interpretando información sobre el hw en Buster

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree-client#105]
No se si tiene que ver con lo resuelto en la issue #94 pero al probar en un debian 10 un migasfree -u, tenemos el siguiente error:
```
************* Interpretando información sobre el hardware... **************
******************************** Fallo
```
Cliente: Debian10 Buster, Server, virtualizado en VirtualBox
Versión del cliente migasfree: 4.17-1
Versión del server: 4.16

Más detalles (modo debug):
```
root@debian10:/etc/apt# cat /tmp/migasfree-client/migasfree-command.err 
--------------------
2019-11-18 13:14:17
Información sobre el hardware: Expecting , delimiter: line 21 column 8 (char 489)
```

**Comment by jact** [comment]
Duplicado de #94
