### ISSUE TITLE
Añadir funciones en utils para obtener variables de /etc/migasfree.conf

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#45]
A la hora de programar scripts (en paquetes p.e.) se me ha dado el caso de tener que saber el nombre del servidor migasfree al que estoy conectado y he usado el código siguiente:
<pre>
_PYTHON_CODE="from migasfree_client.utils import get_config
from migasfree_client import settings
config = get_config(settings.CONF_FILE, 'client')
print config.get('server', 'localhost')
"
_SERVER=$(python -c "$_PYTHON_CODE")
</pre>

Se solicita se añadan las funciones siguientes en utils para hacer el código más legible:
**get_config_server**
**get_config_version**
**get_config_node**, debe devolver:  version@server

De esta manera, si se quiere obtener el nodo, se escribiría:

`_NODE=$(python -c "from migasfree_client.utils import get_config_node; print get_config_node()") `

**Comment by jact** [comment]
La solución está en la incidencia #43, que está disponible desde la versión 4.4 del cliente.

Se trataría de instanciar el objeto MigasfreeClient y acceder a las propiedas que empiezan por **migas_**:

`
import migasfree_client.client
obj = migasfree_client.client.MigasFreeClient()
obj.migas_server
obj.migas_version
`
