### ISSUE TITLE
Administración Compartida

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#47]
En este modelo de administración un equipo es cliente de **varios servidores migasfree**.

Cuando se ejecuta **migasfree –update**, el cliente se conectará al primer servidor que encuentre y realizará el proceso de actualización, despues hará lo mismo con el resto.

![admonshared](https://cloud.githubusercontent.com/assets/247068/4346272/b1972bb0-40f5-11e4-9e6d-e803bd24383f.png)

En el esquema de arrriba, María es administradora de un servidor migasfree donde se conectan 7 ordenadores. María comparte la administración con Miguel de 4 ordenadores. 

Los 4 ordenadores con administración compartida tendrán instalados dos paquetes de configuración de cliente migasfree, uno para el servidor de María y otro para el de Miguel. 

Los otros 3 tendrán sólo el paquete de configuración del cliente del servidor de María.

En este modelo no existen jerarquías, sino simplemente conjuntos de ordenadores a ser administrados por uno o varios administradores.

**Cambios necesarios en el cliente para que esto sea posible**

1.- Desaparece el fichero **/etc/migasfree.conf**. En su lugar, se crearán ficheros de configuración en el directorio /etc/migasfree.conf.d/  
En caso de que no exista ningún fichero de configuración, el cliente debe conectar con localhost (y resto de valores por defecto) para facilitar el aprendizaje al instalar el servidor y cliente por primera vez.

2.-  **Claves** de versión migasfree: Se crearán unas por cada version@servidor. Pueden seguir almacenándose  en /root/.migasfree-keys/

Se aprovechará la comprobación de su no existencia para descargar las claves de versión junto con la **clave de firma de repositorios** (httpp://server/get_key_repositories)

para apt:
<pre>
wget -qO - $_SERVER/get_key_repositories | apt-key add - 
</pre>

para rpm:
<pre>
wget -O $_FILE $_SERVER/get_key_repositories
rpm --import $_FILE
</pre>
3.- Por defecto migasfree –update actualiza contra todos los servidores configurados. Se añadirá un parametro en migasfree para indicar contra que servidor/servidores actualizar de todos los configurados. Este parámetro funcionará de forma semejante tambien en **migasfree-label**, **migasfree-tags** y **migasfree-upload**

4.- Para facilitar un posible traspaso de etiquetas de un servidor a otro, se permitirá ejecutar **migasfree-tags --get** y **migasfree-tags --communicate** mientras se esté ejecutando **migasfree --update**.

**Comment by jact** [comment]
Añade demasiada complejidad y podría ocasionar más problemas que beneficios.
