### ISSUE TITLE
Error si en el servidor no hay repositorios asignados.

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#51]
Si no hay repositorios asignados al equipo se produce un error en el cliente quedándose asignados en el source.list.d/migasfree.list los viejos repositorios. Esto provoca que ya no se produzca la actualización de paquetes (de los repositorios oficiales p.e.).

Lo que debería hacerse es borrrar el fichero migasfree.list (o crear uno vacio), y que el cliente no lo considere como error, ya que no lo es.

**Comment by jact** [comment]
El cambio propuesto es que el cliente informe de lo que le envía el servidor (error 404 si no hay repositorios disponibles) y que se cree un fichero migasfree.list vacío. Así, el comportamiento es más coherente ya que, cada vez que se ejecuta el cliente, se configuran totalmente los repositorios del servidor migasfree en el equipo destino (no se deja una posible configuración anterior porque es posible que esos repositorios ya no existan y esto genere después nuevos errores).
