### ISSUE TITLE
No detecta bien el usuario de la sesión gráfica en Ubuntu 16.04 (Xenial) con Unity

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#56]
Dice que es el usuario root y no el que ha iniciado la sesión gráfica.

**Comment by jact** [comment]
Parece ser que la sesión de Unity no se lanza con el proceso gnome-session sino con el proceso gnome-session-binary. Creo que este cambio es a partir de Gnome 3.14.

**Comment by jact** [comment]
También aplica el problema a **gnome-session-flashback**. Ha cambiado el proceso que lanza la sesión gráfica
