### ISSUE TITLE
Unificar bajo un mismo comando todos los existentes

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#58]
Deben eliminarse los siguientes:

- migasfree-upload
- migasfree-label
- migasfree-tags

Para añadir todas las opciones al comando único **migasfree**.

Ejemplos:

- $ migasfree 
- $ migasfree sync [opciones]
- $ migasfree label
- $ migasfree tags [opciones]
- $ migasfree upload [opciones]
- $ migasfree install [opciones]
- $ migasfree purge [opciones]
- $ migasfree search [opciones]
- $ migasfree register [opciones]

**Comment by jact** [comment]
Este cambio se realizará para la rama **REST-API**.

**Comment by jact** [comment]
https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/
