### ISSUE TITLE
Nombres de equipos en redes con subdominios

### ISSUE THREAD

**Issue by JordiRoman** [migasfree/migasfree-client#70]
Explico la situación. Me he encontrado en mi instalación de Migas con maquinas con el mismo nombre, me explico con un ejemplo

Dos maquinas cuyo nombre completo es el siguiente:
**maquina1.ou1.dominio** y **maquina1.ou2.dominio**

Pero realmente el nombre de las maquinas (lo que contesta con hostname, platform.node() o socket.gethostname() ) es:

**maquina1.ou1** y **maquina1.ou2**

sin embargo en migasfree las 2 maquinas se ven como **maquina1**

El código para obtener el nombre de la maquina es

`return platform.node().split('.')[0]`

pero creo que seria mas correcto  que fuera alguna de las siguientes alternativas para evitar las 'colisiones visuales' de nombres

`return platform.node()`
`return socket.gethostname()`
`return socket.getfqdn()`

**Comment by jact** [comment]
Consideramos como nombre de máquina lo que hay más a la izquierda del nombre completo del equipo. Esta es la definición formal según lo dice el protocolo DNS.

Además, platform.node y socket.gethostname, según el manual de Python, no está muy claro qué pueden devolver: o bien el nombre completo... o bien otra cosa. Por eso, devolvemos únicamente la parte de más a la izquierda del primer punto.

Esta forma de trabajar nos ayuda bastante a la hora de identificar nombres de máquinas repetidos. Para nosotros, esta circunstancia, es un error (cada máquina tiene una etiqueta física con el número de inventario y este debe ser único). Así que, una vez localizados los repetidos, procedemos a solucionar la situación.

No obstante, lo que hace a un equipo único en migasfree, es su UUID, que es el número de serie de la placa base del ordenador. Es por ello que, en el comando migasfree-label, aparecen asociados el UUID y el campo que se haya escogido para identificar a los equipos en el interfaz de migasfree (el CID, el campo nombre, etc).

Si bien es verdad que, en tu caso, la situación es diferente. Tienes varios dominios y nosotros sólo trabajamos con uno.

Pensaremos en alguna forma de conciliar ambos planteamientos...

**Comment by jact** [comment]
El cliente mandará un parámetro (fqdn), basado en el resultado de **socket.getfqdn()**.
