### ISSUE TITLE
Problema de conexión en el cliente al tratar de subir datos al servidor Migasfree

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree-client#71]
Hola!!

Tenemos un problema genérico en un centro donde todos los clientes migasfree presentan el mismo problema ... En todos ellos la consola muestra lo siguiente:

```
************************** Subiendo atributos... ***************************
Código de error HTTP: 500
***************************** Correcto
Traceback (most recent call last):
  File "/usr/bin/migasfree", line 17, in <module>
    migasfree_client.client.main()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/client.py", line 859, in main
    mfc.run()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/client.py", line 836, in run
    self._update_system()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/client.py", line 496, in _update_system
    if len(_request['faultsdef']) > 0:
KeyError: 'faultsdef'

```
Tras haber ejecutado múltiples veces "migasfree -u" varios equipos todos ellos terminan justamente en la misma sección (subiendo atributos, justo antes de ejecutar las fallas).  ¿Puede ser debido a un problema de conectividad o de upload?  ¿puede ser un problema de la infraestructura de red, por tener que balancear entre varías lineas ADSL de salida? ... Hemos hecho un test de velocidad en esos equipos, y aunque la velocidad no es ideal no tiene pintas de que pueda ser ese el problema:

```
# test-velocidad 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Movistar (213.97.8.27)...
Selecting best server based on latency...
Hosted by Wifiber.es SL (Oropesa del Mar) [193.96 km]: 32.387 ms
Testing download speed........................................
Download: 7.31 Mbit/s
Testing upload speed..................................................
Upload: 0.18 Mbit/s
```

En otros centros este problema no se da por lo que parece que el problema viene propiciado por el Zentyal (cortafuegos/proxy) o el router, pero tampoco tiene mucho sentido porque ese mismo Zentyal y router esta puesto en otros muchos centros Vitalinux donde no surge ese problema.

Si se os ocurre a que puede ser debido sería perfecto.
Muchas Gracias de antemano. Saludos!!

**Comment by jact** [comment]
Hay que poner el cliente en modo _debug_ y ver el _log_ (**/var/tmp/migasfree.log**) para saber lo que devuelve el servidor exactamente.

El error que comentas también lo hemos sufrido aquí, cuando hemos tenido problemas de resolución DNS. Puede ser debido a problemas de conexión (tal vez intermitentes) entre los clientes y el servidor.

**Comment by jact** [comment]
Al no tener más noticias sobre la incidencia, la cierro.
