### ISSUE TITLE
Añadir método "availables" al pms

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#76]
Para facilitar el trabajo a los front-end de migasfree-client estaría bien incluir en el pms un método para obtener la lista de los nombres de los paquetes disponibles.

apt-get: 
`apt-cache pkgnames`
yum: 
`yum --quiet list available|awk -F. '{print $1}'|grep -v '^ ' |sed '1d'`
zypper:
`zypper pa|awk -F'|' '{print $3}'`

**Comment by jact** [comment]
El método se va a llamar **available_packages** y devolverá una lista ordenada de los paquetes disponibles en los repositorios definidos en la máquina.
