### ISSUE TITLE
Parseo de las variables en migasfree.conf

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree-client#81]
Hemos detectado que si en archivo de configuración del cliente (/etc/migasfree.conf) una variable tiene un espacio delante (por ejemplo) no se parsea adecuadamente y el cliente falla. Quizás no sea un problema (el archivo debería estar bien y sin espacios...), pero por si acaso lo indicamos. 
Ejemplo. En en Debug hemos puesto un espacio delante, ésto ocurre al hacer un upload por ejemplo:

sudo migasfree-upload -f vx-dga-l-mecanismos_1.0-1_i386.deb -m Lubuntu-14.04
Versión de migasfree upload: 4.15

Opciones de ejecución: /etc/migasfree.conf
	Proyecto: Ubuntu-14.04
	Servidor: 192.168.56.1
Debug = True
	Actualizar paquetes automáticamente: True
	Proxy: None
	Certificado SSL: None
	Proxy caché de paquetes: None
	Depuración: False
	Nombre del ordenador: hpbender
	GUI detallado: True
	PMS: apt-get

	Proyecto: Lubuntu-14.04
	Ubicación: base
	Usuario: admin
	Fichero: vx-dga-l-mecanismos_1.0-1_i386.deb
	Fichero normal: False
	Crear repositorio: True

Autoregistrando ordenador...
Error de curl: Illegal characters found in URL
******************************** Fallo
Error de curl: Illegal characters found in URL
unable to load key file
139992365418144:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: ANY PRIVATE KEY
sh: 2: Debug: not found
Traceback (most recent call last):
  File "/usr/bin/migasfree-upload", line 17, in <module>
    migasfree_client.upload.main()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/upload.py", line 353, in main
    mfu.run()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/upload.py", line 342, in run
    self._upload_file()
  File "/usr/lib/python2.7/dist-packages/migasfree_client/upload.py", line 135, in _upload_file
    upload_file=os.path.abspath(self._file)
  File "/usr/lib/python2.7/dist-packages/migasfree_client/url_request.py", line 134, in run
    key=os.path.join(self._path_keys, self._private_key)
  File "/usr/lib/python2.7/dist-packages/migasfree_client/secure.py", line 76, in wrap
    _fp.write(open('{0}.sign'.format(filename), 'rb').read())
IOError: [Errno 2] No such file or directory: '/tmp/migasfree-client/hpbender.17EECA7F-F15F-11E4-A001-0006620000FF.upload_server_package.sign'

**Comment by jact** [comment]
Efectivamente, como comentas, el fichero debería tener la sintaxis correcta de un fichero .ini.
