### ISSUE TITLE
Eliminar posibles dependencias obligatorias

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#85]
Por ejemplo para instalaciones en servidores, cups y sudo.

**Comment by jact** [comment]
La dependencia con python-cups se ha eliminado, ya que se considera que, en equipos de escritorio estará instalado y en servidores puede que no. Esto no afecta a las funcionalidades principales del cliente que son inventariar software y hardware, y sincronizar el software. La gestión de impresoras es algo secundario.

Para el caso de sudo, por el momento no se puede eliminar por el funcionamiento de migasfree-label, ya que ejecuta un navegador web en modo usuario.
