### ISSUE TITLE
Añadir funcionalidades uuid y cid

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-client#86]
Objetivo: obtener el uuid y cid (Computer ID) mediante el comando migasfree

**Comment by jact** [comment]
Queda pendiente, cuando se redefina el protocolo de comunicación entre cliente y servidor. No obstante, las llamadas podrían ser de la siguiente forma (es sólo una idea...):

* migasfree info uuid
* migasfree info id

**Comment by jact** [comment]
Completado en la rama REST-API del cliente. Las opciones del comando son:

`migasfree info [{id,uuid,name,search}]`
