### ISSUE TITLE
https y http

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree-client#93]
Hace unos meses migramos la comunicación del cliente migasfree con el server a https. Sin embargo detectamos que en ocasiones el firewall del centro bloquea las conexiones (por ejemplo, recientemente un firewall de un centro bloqueaba la comunicación ya que según los que gestionaban el mismo estaba configurado para que se bloqueen conexiones que se negocian con un nivel de ssl inferior a 3 y parece que el cliente migasfree lo estaba haciendo).
La pregunta sería si se podría añadir la feature de que el cliente intente conectarse por http en el caso de fallar la conexión por https. 
Por otro lado sería "degradar" la comunicación, pero si falla por motivos de éste tipo, nos quedamos con clientes "colgados", ya que no podemos acceder a ellos (o modificarles dicha conf en el lado del cliente)

**Comment by jact** [comment]
El cliente de migasfree no establece ninguna versión en concreto de protocolo SSL/TLS. Para ello se apoya en pyCurl que, a su vez, es un _wrapper_ de **curl** (esto es aplicable a los clientes de la versión mayor 4). Dependiendo del sistema operativo base, estará instalado una versión de curl más o menos actualizada, que soporte más o menos protocolos de conexión SSL/TLS.

Hacer parametrizable la versión de SSL/TLS es entrar en demasiados tecnicismos de redes. Si el problema, en vuestro caso, es que se están denegando conexiones en el _firewall_, configurad reglas para que dejen pasar las conexiones de los clientes al servidor.
